"""Added test table

Revision ID: 577d1f5850f8
Revises: 
Create Date: 2018-09-06 21:57:06.262466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577d1f5850f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test')
    # ### end Alembic commands ###
