"""Add client number to Consulting Services touchpoint

Revision ID: 923ea26fba14
Revises: 164d05f99b90
Create Date: 2018-09-12 21:04:27.408298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923ea26fba14'
down_revision = '164d05f99b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConsultingServicesTouchPoint', sa.Column('client_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ConsultingServicesTouchPoint', 'client_number')
    # ### end Alembic commands ###
