"""empty message

Revision ID: f34457beb9f4
Revises: a508d833e981
Create Date: 2018-09-09 21:57:04.197292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34457beb9f4'
down_revision = 'a508d833e981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BESTouchpoint',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('lfdn', sa.Integer(), nullable=True),
    sa.Column('client_number', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('p_spec', sa.Integer(), nullable=True),
    sa.Column('business_area', sa.String(length=50), nullable=True),
    sa.Column('project_cc', sa.Integer(), nullable=True),
    sa.Column('handling_unit', sa.String(length=100), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q4', sa.Integer(), nullable=True),
    sa.Column('q6', sa.String(length=3000), nullable=True),
    sa.Column('survey_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('lfdn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BESTouchpoint')
    # ### end Alembic commands ###
